# Uebung Calculation Gain
Zu Lesson4 Decision Trees: 16.CalculatingInformationGain

Unterlagen siehe onenote: "Lesson4: Decision Trees!"

## Aufgabe

Berechne fuer alle moeglichen Splits (Split zwischen Werten innerhalb der Attribute) den Information gain

## Gegeben

csv-file ml-bugs.csv

Lade csv-File mit 2 Attributen:m

    Attribut1: Color. Werte: Green, Blue, Green

    (Attribut2: Length. Werte: float numbers) -> splitte in Attribut 2a und 2b

    Attribut2a: length<17

    Attribut2b: lenght<20

Target: Species: y1=Mobus, y2=Lobgus

# Algorithmus

In [9]:
#import numpy
import numpy as np
import pandas as pd

csv-Datei laden

In [12]:
df = dfmy = pd.read_csv('C:\\ThomasKraemer\\OneDrive\\03_Programmieren\\01_Workspaces\\Eclipse\\UdacityPyTest2\\ml-bugs.csv')
df

Species  Color  Length (mm)
0    Mobug  Brown         11.6
1    Mobug   Blue         16.3
2    Lobug   Blue         15.1
3    Lobug  Green         23.7
4    Lobug   Blue         18.4
5    Lobug  Brown         17.1
6    Mobug  Brown         15.7
7    Lobug  Green         18.6
8    Lobug   Blue         22.9
9    Lobug   Blue         21.0
10   Lobug   Blue         20.5
11   Mobug  Green         21.2
12   Mobug  Brown         13.8
13   Lobug   Blue         14.5
14   Lobug  Green         24.8
15   Mobug  Brown         18.2
16   Lobug  Green         17.9
17   Lobug  Green         22.7
18   Mobug  Green         19.9
19   Mobug   Blue         14.6
20   Mobug   Blue         19.2
21   Lobug  Brown         14.1
22   Lobug  Green         18.8
23   Mobug   Blue         13.1

Konvertiere nach numpy

In [493]:
y=df['Species'].to_numpy()
y

array(['Mobug', 'Mobug', 'Lobug', 'Lobug', 'Lobug', 'Lobug', 'Mobug',
       'Lobug', 'Lobug', 'Lobug', 'Lobug', 'Mobug', 'Mobug', 'Lobug',
       'Lobug', 'Mobug', 'Lobug', 'Lobug', 'Mobug', 'Mobug', 'Mobug',
       'Lobug', 'Lobug', 'Mobug'], dtype=object)

In [494]:
color=df['Color'].to_numpy()
color

array(['Brown', 'Blue', 'Blue', 'Green', 'Blue', 'Brown', 'Brown',
       'Green', 'Blue', 'Blue', 'Blue', 'Green', 'Brown', 'Blue', 'Green',
       'Brown', 'Green', 'Green', 'Green', 'Blue', 'Blue', 'Brown',
       'Green', 'Blue'], dtype=object)

In [495]:
length=df['Length (mm)'].to_numpy()
length

array([11.6, 16.3, 15.1, 23.7, 18.4, 17.1, 15.7, 18.6, 22.9, 21. , 20.5,
       21.2, 13.8, 14.5, 24.8, 18.2, 17.9, 22.7, 19.9, 14.6, 19.2, 14.1,
       18.8, 13.1])

## Entropie State0

In [496]:
# sumy1 = Summe(y1)
helper = y[y=='Mobug']
print(helper)
sumy1 = helper.size
sumy1


['Mobug' 'Mobug' 'Mobug' 'Mobug' 'Mobug' 'Mobug' 'Mobug' 'Mobug' 'Mobug'
 'Mobug']


10

In [497]:
# sumy2 = Summe(y2)
helper = y[y=='Lobug']
print(helper)
sumy2 = helper.size
sumy2

['Lobug' 'Lobug' 'Lobug' 'Lobug' 'Lobug' 'Lobug' 'Lobug' 'Lobug' 'Lobug'
 'Lobug' 'Lobug' 'Lobug' 'Lobug' 'Lobug']


14

In [498]:
p1 = sumy1/(sumy1+sumy2)
p2 = sumy2/(sumy1+sumy2)
print(p1)
print(p2)

0.4166666666666667
0.5833333333333334


In [499]:
E0 = -1*(p1*np.log2(p1)+p2*np.log2(p2))
E0

0.9798687566511528

## Entropie Split1

### ESplit1Blue

In [500]:
y1ones=np.zeros((y.size,1))
for i in range(0,y.size) :
    if (y[i] == 'Mobug'):
       y1ones[i] = 1
#print(y1ones)

In [501]:
y2ones=np.zeros((y.size,1))
for i in range(0,y.size) :
    if (y[i] == 'Lobug'):
       y2ones[i] = 1
#print(y2ones)

In [502]:
Blueones=np.zeros((color.size,1))
for i in range(0,y.size) :
    if (color[i] == 'Blue'):
       Blueones[i] = 1
#Blueones

In [503]:
Greenones=np.zeros((color.size,1))
for i in range(0,y.size) :
    if (color[i] == 'Green'):
       Greenones[i] = 1
#Greenones

In [504]:
Brownones=np.zeros((color.size,1))
for i in range(0,y.size) :
    if (color[i] == 'Brown'):
       Brownones[i] = 1
#Brownones

In [505]:
BlueAndy1=np.dot(y1ones.reshape(1,y1ones.size),Blueones.reshape((Blueones.size,1)))
BlueAndy1

array([[4.]])

In [506]:
BlueAndy2=np.dot(y2ones.reshape(1,y2ones.size),Blueones.reshape((Blueones.size,1)))
BlueAndy2

array([[6.]])

In [507]:
GreenAndy1=np.dot(y1ones.reshape(1,y1ones.size),Greenones.reshape((Greenones.size,1)))
GreenAndy1

array([[2.]])

In [508]:
GreenAndy2=np.dot(y2ones.reshape(1,y2ones.size),Greenones.reshape((Greenones.size,1)))
GreenAndy2

array([[6.]])

In [509]:
BrownAndy1=np.dot(y1ones.reshape(1,y1ones.size),Brownones.reshape((Brownones.size,1)))
BrownAndy1

array([[4.]])

In [510]:
BrownAndy2=np.dot(y2ones.reshape(1,y2ones.size),Brownones.reshape((Brownones.size,1)))
BrownAndy2

array([[2.]])

In [511]:
p1=np.ndarray.item(BlueAndy1/(BlueAndy1+BlueAndy2))
p1

0.4

In [512]:
p2=np.ndarray.item(BlueAndy2/(BlueAndy1+BlueAndy2))
p2

0.6

In [513]:
EBlue= -1*(p1*np.log2(p1)+p2*np.log2(p2))
EBlue

0.9709505944546686

In [514]:
#Green and Brown

In [515]:
GreenBrowny1 = GreenAndy1 + BrownAndy1
GreenBrowny1

array([[6.]])

In [516]:
GreenBrowny2 = GreenAndy2 + BrownAndy2
GreenBrowny2

array([[8.]])

In [517]:
p1=np.ndarray.item(GreenBrowny1/(GreenBrowny1+GreenBrowny2))
p1

0.42857142857142855

In [518]:
p2=np.ndarray.item(GreenBrowny2/(GreenBrowny1+GreenBrowny2))
p2

0.5714285714285714

In [519]:
EGreenBrown = -1*(p1*np.log2(p1)+p2*np.log2(p2))
EGreenBrown

0.9852281360342515

In [520]:
IGBlue = E0 - 0.5*(EBlue + EGreenBrown)
IGBlue

0.0017793914066928096

In [521]:
GreenAndy1

array([[2.]])

In [522]:
GreenAndy2

array([[6.]])

In [523]:
p1=np.ndarray.item(GreenAndy1/(GreenAndy1+GreenAndy2))
p1

0.25

In [524]:
p2=np.ndarray.item(GreenAndy2/(GreenAndy1+GreenAndy2))
p2

0.75

In [525]:
EGreen= -1*(p1*np.log2(p1)+p2*np.log2(p2))
EGreen

0.8112781244591328

In [526]:
# Blue and Green
GreenBlue1 = GreenAndy1 + BlueAndy1
GreenBlue1

array([[6.]])

In [527]:
GreenBlue2 = GreenAndy2 + BlueAndy2
GreenBlue2

array([[12.]])

In [528]:
p1=np.ndarray.item(GreenBlue1/(GreenBlue1+GreenBlue2))
p1

0.3333333333333333

In [529]:
p2=np.ndarray.item(GreenBlue2/(GreenBlue1+GreenBlue2))
p2

0.6666666666666666

In [530]:
EGreenBlue = -1*(p1*np.log2(p1)+p2*np.log2(p2))
EGreenBlue

0.9182958340544896

In [531]:
p1=np.ndarray.item(BrownAndy2/(BrownAndy1+BrownAndy2))
p2

0.6666666666666666

In [532]:
EBrown= -1*(p1*np.log2(p1)+p2*np.log2(p2))
EBrown

0.9182958340544896

In [533]:
IGBrown = E0 - 0.5*(EBrown + EGreenBlue)
IGBrown

0.06157292259666325

In [534]:
# Blue and Green
BrownBlue1 = BrownAndy1 + BlueAndy1
BrownBlue1

array([[8.]])

In [535]:
BrownBlue2 = BrownAndy2 + BlueAndy2
BrownBlue2

array([[8.]])

In [536]:
p1=np.ndarray.item(BrownBlue1/(BrownBlue1+BrownBlue2))
p1

0.5

In [537]:
p2=np.ndarray.item(BrownBlue2/(BrownBlue1+BrownBlue2))
p2

0.5

In [538]:
EBrownBlue = -1*(p1*np.log2(p1)+p2*np.log2(p2))
EBrownBlue

1.0

In [539]:
IGGreen = E0 - 0.5*(EGreen + EBrownBlue)
IGGreen

0.07422969442158633

## Y2

In [540]:
length

array([11.6, 16.3, 15.1, 23.7, 18.4, 17.1, 15.7, 18.6, 22.9, 21. , 20.5,
       21.2, 13.8, 14.5, 24.8, 18.2, 17.9, 22.7, 19.9, 14.6, 19.2, 14.1,
       18.8, 13.1])

In [541]:
SmallY1nones=np.zeros((color.size,1))
for i in range(0,y.size) :
    if (y[i] == 'Mobug') & (length[i]<17):
       SmallY1nones[i] = 1
#SmallY1nones

In [542]:
SmallY1Sum = SmallY1nones.sum()
SmallY1Sum

6.0

In [543]:
SmallY2nones=np.zeros((color.size,1))
for i in range(0,y.size) :
    if (y[i] == 'Lobug') & (length[i]<17):
       SmallY2nones[i] = 1
#SmallY2nones

In [544]:
SmallY2Sum = SmallY2nones.sum()
SmallY2Sum

3.0

In [545]:
p1=SmallY1Sum/(SmallY1Sum + SmallY2Sum)

In [546]:
p2=SmallY2Sum/(SmallY1Sum + SmallY2Sum)

In [547]:
ESmall = -1*(p1*np.log2(p1)+p2*np.log2(p2))
ESmall

0.9182958340544896

In [548]:
SmallY1nonesRest=np.zeros((color.size,1))
for i in range(0,y.size) :
    if (y[i] == 'Mobug') & (length[i]>17):
       SmallY1nonesRest[i] = 1
#SmallY1nonesRest

In [549]:
SmallY1SumRest = SmallY1nonesRest.sum()
SmallY1SumRest

4.0

In [550]:
SmallY2nonesRest=np.zeros((color.size,1))
for i in range(0,y.size) :
    if (y[i] == 'Lobug') & (length[i]>17):
       SmallY2nonesRest[i] = 1
#SmallY2nonesRest

In [551]:
SmallY2SumRest = SmallY2nonesRest.sum()
SmallY2SumRest

11.0

In [552]:
p1=SmallY1SumRest/(SmallY1SumRest + SmallY2SumRest)

In [553]:
p2=SmallY2SumRest/(SmallY1SumRest + SmallY2SumRest)

In [554]:
ESmallRest = -1*(p1*np.log2(p1)+p2*np.log2(p2))
ESmallRest

0.8366407419411672

In [555]:
IGSmall = E0 - 0.5* (ESmall+ESmallRest)
IGSmall

0.10240046865332442

In [556]:
E0

0.9798687566511528

In [557]:
BigY1nones=np.zeros((color.size,1))
for i in range(0,y.size) :
    if (y[i] == 'Mobug') & (length[i]<20):
       BigY1nones[i] = 1
#BigY1nones

In [558]:
BigY1Sum = SmallY1nones.sum()
BigY1Sum

6.0

In [559]:
BigY2nones=np.zeros((color.size,1))
for i in range(0,y.size) :
    if (y[i] == 'Lobug') & (length[i]<20):
       BigY2nones[i] = 1
BigY2nones

array([[0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.]])

In [560]:
BigY2Sum = SmallY2nones.sum()
BigY2Sum

3.0

IGSmall = ? 

In [561]:
BigY1nonesRest=np.zeros((color.size,1))
for i in range(0,y.size) :
    if (y[i] == 'Mobug') & (length[i]>20):
       BigY1nonesRest[i] = 1
BigY1nonesRest

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [562]:
BigY1SumRest = BigY1nonesRest.sum()
BigY1SumRest

1.0

In [563]:
BigY2nonesRest=np.zeros((color.size,1))
for i in range(0,y.size) :
    if (y[i] == 'Lobug') & (length[i]>20):
       BigY2nonesRest[i] = 1
BigY2nonesRest

array([[0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [564]:
BigY2SumRest = BigY2nonesRest.sum()
BigY2SumRest

6.0

In [565]:
p1=BigY1Sum/(BigY1Sum + BigY2Sum)

In [566]:
p2=BigY2Sum/(BigY1Sum + BigY2Sum)

In [567]:
EBig = -1*(p1*np.log2(p1)+p2*np.log2(p2))
EBig

0.9182958340544896

In [568]:
p1=BigY1SumRest/(BigY1SumRest + BigY2SumRest)

In [569]:
p2=BigY2SumRest/(BigY1SumRest + BigY2SumRest)

In [570]:
EBigRest = -1*(p1*np.log2(p1)+p2*np.log2(p2))
EBigRest

0.5916727785823275

In [571]:
IGBig = E0 - 0.5*(EBig+EBigRest)
IGBig

0.2248844503327443

In [572]:
BlueonesAndY1=np.zeros((color.size,1))
for i in range(0,y.size) :
    if (color[i] == 'Blue') & (y[i]=='Mobug'):
       BlueonesAndY1[i] = 1
BlueonesAndY1Sum = BlueonesAndY1.sum()
BlueonesAndY1Sum

4.0

In [573]:
GreenonesAndY1=np.zeros((color.size,1))
for i in range(0,y.size) :
    if (color[i] == 'Green') & (y[i]=='Mobug'):
       GreenonesAndY1[i] = 1
GreenonesAndY1Sum = GreenonesAndY1.sum()
GreenonesAndY1Sum

2.0

In [574]:
GreenonesAndY2=np.zeros((color.size,1))
for i in range(0,y.size) :
    if (color[i] == 'Green') & (y[i]=='Lobug'):
       GreenonesAndY2[i] = 1
GreenonesAndY2Sum = GreenonesAndY2.sum()
GreenonesAndY2Sum

6.0

In [575]:
BrownonesAndY1=np.zeros((color.size,1))
for i in range(0,y.size) :
    if (color[i] == 'Brown') & (y[i]=='Mobug'):
       BrownonesAndY1[i] = 1
BrownonesAndY1Sum = BrownonesAndY1.sum()
BrownonesAndY1Sum

4.0

In [576]:
BrownonesAndY2=np.zeros((color.size,1))
for i in range(0,y.size) :
    if (color[i] == 'Brown') & (y[i]=='Lobug'):
       BrownonesAndY2[i] = 1
BrownonesAndY2Sum = BrownonesAndY2.sum()
BrownonesAndY2Sum

2.0